server:
  port: 8081

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

spring:
  application:
    name: AUTH-SERVICE
  security:
    user:
      password-ecoder: bcrypt
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    loadbalancer:
      retry:
        enabled: true



application-title: Auth Service API
application-description: Authentication and Authorization Service for WorkStreamERP
application-version: 1.0.0
application-license: Apache 2.0

jwt:
  secret: sEwB7lNM2DQY/K3CUG3R3jQ+5tsezgzNOnSgkAHHPguh2VVn2Bfi4xaX0jXw1VIZ7jvOUMSoHeu+totSMOY7Ow==
  expiration: 3600000
  refresh-expiration: 604800000

internal:
  token: 8nwh07iuSmlU0urIm2SUi4HPo9C1jj1tglJvfmVNfag=

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.mycompany.discoveryserver: TRACE

grpc:
  client:
    user-service:
      host: localhost
      port: 50051