spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/erp_user_db
    username: postgres
    password: admin1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

server:
  port: 8082


