spring:
  application:
    name: PROJECT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/erp_project_db
    username: postgres
    password: admin1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      register-with-eureka: true
  instance:
    preferIpAddress: true


jwt:
  secret: sEwB7lNM2DQY/K3CUG3R3jQ+5tsezgzNOnSgkAHHPguh2VVn2Bfi4xaX0jXw1VIZ7jvOUMSoHeu+totSMOY7Ow==
  expiration: 3600000
