spring:
  application:
    name: discovery-server
  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

