CREATE TABLE "public"."erp_projects" (

  "id" varchar(36) COLLATE "pg_catalog"."default" NOT NULL,
  "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "description" varchar(255) COLLATE "pg_catalog"."default",
  "client_id" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "client_name" varchar(255) COLLATE "pg_catalog"."default",
  "end_date" date,
  "start_date" date,
  "status" int2 NOT NULL,


  "is_deleted" bool NOT NULL DEFAULT false,
  "deleted_at" timestamp(6),
  "deleted_by" varchar(36) COLLATE "pg_catalog"."default",


  "created_at" timestamp(6) NOT NULL,
  "created_by" varchar(36) COLLATE "pg_catalog"."default" NOT NULL,

  "updated_at" timestamp(6) NOT NULL,
  "updated_by" varchar(36) COLLATE "pg_catalog"."default" NOT NULL,

  CONSTRAINT "erp_projects_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uk4ryugigl6pka58aw092qf2poh" UNIQUE ("name"),
  CONSTRAINT "erp_projects_status_check" CHECK (status >= 0 AND status <= 4)
)
;

ALTER TABLE "public"."erp_projects"
  OWNER TO "postgres";


CREATE TABLE "public"."erp_projectmembers" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 MINVALUE  1 MAXVALUE 9223372036854775807 START 1 CACHE 1),
  "project_id" varchar(36) COLLATE "pg_catalog"."default" NOT NULL,
  "user_id" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "role" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,

  "added_at" timestamp(6) NOT NULL,
  "added_by" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,

  CONSTRAINT "erp_projectmembers_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fk9dlkju3u3s6287d96o6846tym" FOREIGN KEY ("project_id") REFERENCES "public"."erp_projects" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "uk7n6n21v7db3udfj2byum3ynbp" UNIQUE ("user_id"),
  CONSTRAINT "erp_projectmembers_role_check" CHECK (role::text = ANY (ARRAY['ADMIN'::character varying, 'CLIENT'::character varying, 'FREELANCER'::character varying]::text[]))
)
;

ALTER TABLE "public"."erp_projectmembers"
  OWNER TO "postgres";